### ISSUE TITLE
Support until-found in Firefox / Opera / Safari like in Chrome

### ISSUE THREAD

**Issue by tzeumer** [corentin-gautier/Accordion-Blocks#3]
The "browser compatibility" section for [hidden attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) shows that only Chrome supports until-found (thank for implementing this again). 

For Firefox and other browser one has to implement it differently. Since not finding thing in accordions is really bad usability it'd be great if there were a solution. The simplest thing were if the script could catch that a user starts a search in the browser and then just opens all (unopened) accordions.

But maybe it simply is just a shortcoming of the browser implementing the standard as intended and it is best to wait for a fix by the browser vendors.

**Comment by corentin-gautier** [comment]
Hi @tzeumer 

I added some support for this by detecting ctrl/cmd + F and opening all the accordions when that happens. It's not perfect though, it won't detect using search through menus.

I guess now we should wait for browser support !

**Comment by tzeumer** [comment]
Thank you very much! :)
